### ISSUE TITLE
FSP To-Do List

### ISSUE THREAD

**Issue by mwmadsen67** [Jim-Heftypants/newChess.com#1]
# Wiki Page Home

- [ ] Is the first page you see upon entering the wiki
- [ ] Contains a welcome message
- [ ] Contains a link/placeholder for a link to the live page
- [ ] All links in the right sidebar should contain each wiki page and link to the correct page
- [ ] Correctly formatted
    - [ ] each wiki page is listed in bullet points
    - [ ] all links route the correct page

---

# Database Schema

- [ ] Contains correct datatypes
- [ ] Contains appropriate constraints/details
    - [ ] primary key
    - [ ] not null
    - [ ] unique
    - [ ] indexed
    - [ ] foreign key
- [ ] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
  - [ ] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [ ] Correctly formatted
    - [ ] schema is written in a table format
    - [ ] the table's name are lowercased, snake_cased and `back_ticked`
    - [ ] the table header column names are bolded
    - [ ] columns names are lowercased and snaked_cased and `back_ticked`

---

# Sample State

- [ ] State shape is flat!
- [ ] State's keys are camelCased
- [ ] All keys within the values in the state are accessible in the schema
- [ ] Correctly formatted
    - [ ] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
    - [ ] Top level slices
        - [ ] `entities`
        - [ ] `session`
        - [ ] `errors` (here or in `ui`)
        - [ ] `ui` (if needed)
    - [ ] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice

---

# MVP List

- [ ] Should have 7 MVPs.
    - [ ] 3 of those are User Auth, Heroku, and Production README.
    - [ ] The other 4 are from the [MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) or they have clarified them with you
- [ ] Contains a description sentence of the app
- [ ] Includes two to three detailed bullets on functionality and presentation of feature
- [ ] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [ ] Estimates how long it will take the code each MVP
- [ ] Correctly formatted
    - [ ] MVPs are listed in an ordered list
    - [ ] Each MVP is broken down into bullet points

---

# Backend Routes

- [ ] Contains the following sections: HTML, API Endpoints(Backend)
- [ ] Each route has a description
- [ ] API Endpoint routes contains wildcard variables written in `snake_case`
- [ ] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [ ] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint because that info comes through the post show

---

# Frontend Routes

- [ ] Frontend routes contains wildcard variables written in `camelCase`
- [ ] Correctly formatted
    - [ ] Routes are displayed with `inline coding text` (backticks)

**Comment by mwmadsen67** [comment]
Hey Nick, I'm going to list out some points here based on my first look at your design docs. Some of this will be repeated from what we talked about earlier but this way you can refer back to this rather than try to remember a conversation.

**Schema**: Try to format this similarly to the bluebird example. In particular, I'd like to see lines below each table showing where foreign keys point to and how columns are indexed. The user table should have a session_token and password_digest for user_auth. The friends table should be a joins table between users, so it should have 2 foreign_keys, also you should think about how to use this table to implement friend requests. Like we talked about, you should have a table for games as well, and this would have a string of the move list, foreign_keys for user_ids and any other information you want to store about games. Learning goals is another thing we talked about that you should make a table for.

**State Shape:** The entities state should also have a slice of state for friends, and then games and learning goals for when you add those to your schema as well. Otherwise it looks good and is well formatted.

**MVP-List:** Your MVP list should have more detailed information underneath each MVP. Check the bluebird example for how it was done there. Writing these out will help you plan each phase of your project and help keep you on track to turning in a finished project.

Overall this is a decent start on your design docs but still needs some work. Feel free to post any questions in this thread.

**Comment by Nick-Sercel** [comment]
I reworked all my components, mind taking another look?

**Comment by mwmadsen67** [comment]
Awesome, it's definitely looking better.

**Schema:** I would stay away from keeping a game_ids column in your users table. Since your games have user_ids, you can simply use a has_many games association to get the game_ids array in your state shape later. Also if your friends table is going to work through friend requests, you will need a boolean that indicates whether it has been accepted or it's pending. Everything else looks great.

State shape and MVP List looks great.

**Backend Routes:** The api/users/games route is not a valid route. If you want a route for finding a users games it would be api/users/:user_id/games, and I would list that route under games as well. It still says chirps in the delete friends route. Everything else looks good.

**Frontend Routes:** Everything looks good to me, although I'm not sure you would need a friend form component. It could just be a button next to a users name that sends a friend request.

Great work Nick!
